name: cron
# on:
#   schedule:
#     # KST 12
#     - cron: '0 3 * * *'
on:
  push:
    branches:
      - master
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@master

    - name: Cache node modules
      uses: actions/cache@v2.0.0
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-

    - name: Install
      run: npm install

    - name: Start
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: npm start
