name: cron
# on:
#   schedule:
#     # KST 12
#     - cron: '0 3 * * *'
on:
  push:
    branches:
      - master
jobs:
  cron:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v2.0.0
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
      - name: Start
        run: |
          npm start
